Repository IllumiDesk/illumidesk, pull requests merged in 2020-05, with the labels that each got.

#32 Update imports and modify authenticator entry point setup
  ansible/roles/jupyterhub/files/jupyterhub_config_lti11.py
  src/illumidesk/authenticators/authenticator.py
  src/setup.py
Labels: chore

#34 Remove ansible-lint
  .pre-commit-config.yaml
  .travis/script.sh
  Makefile
  dev-requirements.txt
Labels: fix

#35 Update changelog for release v0.2.3
  CHANGELOG.md
  package.json
  src/_version.py
Labels: documentation

#38 Add grades submission feature (lti11)
  .gitignore
  ansible/roles/jupyterhub/files/jupyterhub_config_lti11.py
  ansible/roles/nbgrader/files/server_extensions/formgrader/static/js/manage_assignments.js
  ansible/roles/nbgrader/files/server_extensions/formgrader/templates/manage_assignments.tpl
  ansible/roles/nbgrader/tasks/main.yml
  ansible/roles/notebooks/templates/Dockerfile.grader.j2
  src/illumidesk/authenticators/authenticator.py
  src/illumidesk/handlers/__init__.py
  src/illumidesk/handlers/lms_grades.py
  src/setup.py
  tests/illumidesk/authenticators/test_lti11_authenticator.py
  tests/illumidesk/handlers/test_lms_grades.py
Labels: enhancement

#40 Release v0.3.0
  CHANGELOG.md
  package.json
  src/_version.py
Labels: chore

#39 Added yellowbrick library to requrements.txt
  ansible/roles/notebooks/files/requirements.txt
Labels: dependencies

#43 Rsync ignore
  ansible/roles/illumidesk/tasks/main.yml
Labels: chore

#42 Create Traefik's rules.toml with copy
  ansible/roles/reverse-proxy/files/rules.toml
  ansible/roles/reverse-proxy/tasks/main.yml
Labels: chore

#44 Update mount root environment variable documentation
  README.md
  ansible/group_vars/all.yml
  ansible/roles/setup_course/templates/env.setup_course.j2
  src/illumidesk/handlers/lms_grades.py
  src/illumidesk/setup_course/course.py
  tests/illumidesk/setup_course/test_app.py
  tests/illumidesk/setup_course/test_course.py
Labels: documentation

#46 Change services menu
  ansible/roles/jupyterhub/files/share/templates/page.html
Labels: enhancement

#47 Release 0.3.1
  CHANGELOG.md
  package.json
  src/_version.py
Labels: chore

#48 Adds helper text in the assignment creation modal
  ansible/roles/nbgrader/files/server_extensions/formgrader/static/js/manage_assignments.js
Labels: enhancement

#49 Release 0.3.2
  CHANGELOG.md
  package.json
  src/_version.py
Labels: chore

#53 Do not use initial course service when LTI is enabled
  README.md
  ansible/roles/jupyterhub/files/jupyterhub_config_lti11.py
  ansible/roles/jupyterhub/tasks/main.yml
  ansible/roles/jupyterhub/templates/docker-compose.yml.j2
  ansible/roles/jupyterhub/templates/env.jhub.j2
Labels: enhancement

#54 Release 0.3.3
  CHANGELOG.md
  package.json
  src/_version.py
Labels: chore

#41 Fixes grades submission for moodle
  ansible/roles/jupyterhub/files/jupyterhub_config_lti11.py
  ansible/roles/jupyterhub/templates/env.jhub.j2
  src/illumidesk/handlers/lms_grades.py
  src/setup.py
  tests/illumidesk/handlers/test_lms_grades.py
Labels: fix

#55 Release 0.3.4
  CHANGELOG.md
  package.json
  src/_version.py
Labels: chore

#58 Add missing setup-course dependencies
  ansible/roles/setup_course/files/Dockerfile
Labels: dependencies

#60 Release 0.3.5
  CHANGELOG.md
  package.json
  src/_version.py
Labels: chore

#61 Release 0.4.0
  CHANGELOG.md
  package.json
  src/_version.py
Labels: chore

#62 Remove ignore package-lock.json
  .gitignore
  package-lock.json
  package.json
Labels: chore

#64 Refactor constants
  .gitignore
  src/illumidesk/authenticators/constants.py
  src/illumidesk/authenticators/utils.py
  src/illumidesk/authenticators/validator.py
Labels: refactor

#67 Rename network env var for consistency
  README.md
  ansible/roles/setup_course/templates/env.setup_course.j2
  src/illumidesk/setup_course/course.py
Labels: refactor

#68 Ignore patch coverages from codecov
  codecov.yml
Labels: chore

#66 Refactor lis username checks and add tests
  grades-sender.lock
  src/illumidesk/authenticators/authenticator.py
  tests/illumidesk/authenticators/test_lti11_authenticator.py
Labels: refactor

#65 Handle missing lis arguments with learner launch requests
  grades-sender.lock
  src/illumidesk/authenticators/authenticator.py
  tests/illumidesk/authenticators/test_lti11_authenticator.py
  tests/illumidesk/authenticators/test_lti11_validator.py
Labels: fix

#70 Revert ansible to 2.9.9
  requirements.txt
Labels: fix

#77 Release 0.4.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/_version.py
Labels: chore

#76 Use cull idle servers package
  ansible/roles/jupyterhub/files/jupyterhub_config_fu.py
  ansible/roles/jupyterhub/files/requirements.txt
Labels: refactor

#78 Update cull idle server configuration to LTI 1.1 config
  ansible/roles/jupyterhub/files/jupyterhub_config_lti11.py
  ansible/roles/jupyterhub/templates/Dockerfile.jhub.j2
Labels: refactor

#75 Feature to add a postgres service for labs
  README.md
  ansible/group_vars/all.yml
  ansible/hosts.hddata
  ansible/roles/jupyterhub/tasks/main.yml
  ansible/roles/jupyterhub/templates/docker-compose.yml.j2
  ansible/roles/notebooks/files/requirements.txt
Labels: enhancement

#79 Release 0.5.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/_version.py
Labels: chore

#80 Release 0.6.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/_version.py
Labels: chore

#84 Add some unit tests
  src/illumidesk/tests/illumidesk/authenticators/test_utils.py
  src/illumidesk/tests/illumidesk/spawners/test_illumidesk_dockerspawner.py
Labels: tests

#86 Add jupyterhub api token to cull idle service
  ansible/roles/jupyterhub/files/jupyterhub_config_fu.py
  ansible/roles/jupyterhub/files/jupyterhub_config_lti11.py
  ansible/roles/jupyterhub/files/jupyterhub_config_lti13.py
Labels: fix

#88 Add tests and update docs for missing environment variable used with rolling updates
  README.md
  ansible/hosts.example
  ansible/roles/setup_course/templates/env.setup_course.j2
  src/illumidesk/setup_course/app.py
  src/illumidesk/setup_course/utils.py
  src/illumidesk/tests/conftest.py
  src/illumidesk/tests/illumidesk/setup_course/test_app.py
  src/illumidesk/tests/illumidesk/setup_course/test_course.py
  src/illumidesk/tests/illumidesk/setup_course/test_utils.py
Labels: tests

#89 Release 0.6.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/_version.py
Labels: chore

#90 Documentation updates for Postgres lab and LTI 1.3 customization options
  README.md
  ansible/hosts.example
Labels: documentation

#87 Moves tests folder
  .travis/script.sh
  src/illumidesk/apis/jupyterhub_api.py
  src/illumidesk/handlers/lti.py
  src/illumidesk/tests/illumidesk/handlers/test_lti13_config_handler.py
  src/illumidesk/tests/illumidesk/setup_course/__init__.py
  src/illumidesk/tests/illumidesk/spawners/__init__.py
  src/illumidesk/tests/illumidesk/spawners/test_illumidesk_dockerspawner.py
  src/setup.py
  src/tests/__init__.py
  src/tests/illumidesk/__init__.py
  src/tests/illumidesk/apis/__init__.py
  src/tests/illumidesk/apis/test_jupyterhub_api.py
  src/tests/illumidesk/authenticators/__init__.py
  src/tests/illumidesk/authenticators/test_lti11_authenticator.py
  src/tests/illumidesk/authenticators/test_lti11_handlers.py
  src/tests/illumidesk/authenticators/test_lti11_validator.py
  src/tests/illumidesk/authenticators/test_lti13_authenticator.py
  src/tests/illumidesk/authenticators/test_lti13_validator.py
  src/tests/illumidesk/authenticators/test_utils.py
  src/tests/illumidesk/conftest.py
  src/tests/illumidesk/factory.py
  src/tests/illumidesk/handlers/__init__.py
  src/tests/illumidesk/handlers/test_lms_grades.py
  src/tests/illumidesk/handlers/test_lti13_config_handler.py
  src/tests/illumidesk/mocks.py
  src/tests/illumidesk/setup_course/__init__.py
  src/tests/illumidesk/setup_course/test_app.py
  src/tests/illumidesk/setup_course/test_course.py
  src/tests/illumidesk/setup_course/test_utils.py
  src/tests/illumidesk/spawners/__init__.py
  src/tests/illumidesk/spawners/test_illumidesk_dockerspawner.py
Labels: chore, tests

#91 Update codecov settings into tests/app projects
  codecov.yml
  src/tests/illumidesk/authenticators/test_lti11_handlers.py
  src/tests/illumidesk/handlers/test_lti13_config_handler.py
Labels: chore
