Repository IllumiDesk/illumidesk, pull requests merged in 2020-09, with the labels that each got.

#309 Remove image by role
  README.md
  ansible/group_vars/all.yml
  ansible/roles/jupyterhub/files/jupyterhub_config_base.py
  ansible/roles/jupyterhub/files/jupyterhub_config_lti11.py
  ansible/roles/jupyterhub/files/jupyterhub_config_lti13.py
  src/illumidesk/apis/jupyterhub_api.py
  src/illumidesk/apis/setup_course_service.py
  src/illumidesk/authenticators/handlers.py
  src/illumidesk/authenticators/utils.py
  src/illumidesk/authenticators/validator.py
  src/illumidesk/grades/handlers.py
  src/illumidesk/lti13/auth.py
  src/illumidesk/lti13/handlers.py
  src/illumidesk/setup_course/app.py
  src/illumidesk/setup_course/course.py
  src/illumidesk/spawners/spawners.py
  src/tests/illumidesk/conftest.py
  src/tests/illumidesk/spawners/test_hooks.py
  src/tests/illumidesk/spawners/test_illumidesk_dockerspawner.py
Labels: refactor

#312 Add git initialization in shared directory
  src/illumidesk/setup_course/course.py
  src/tests/illumidesk/setup_course/test_course.py
Labels: feature

#313 Update ansible vars and env vars with new image references
  README.md
  ansible/group_vars/all.yml
  ansible/roles/jupyterhub/templates/env.jhub.j2
  ansible/roles/setup_course/templates/env.setup_course.j2
  ansible/roles/workspaces/tasks/main.yml
Labels: refactor

#315 Update jupyterhub base image with py3.8
  ansible/group_vars/all.yml
Labels: dependencies

#314 Update base spawner config setting with image env var
  ansible/roles/jupyterhub/files/jupyterhub_config_base.py
  src/illumidesk/setup_course/course.py
  src/tests/illumidesk/conftest.py
Labels: refactor

#317 Add announcement for pilot environments
  ansible/group_vars/all.yml
  ansible/hosts.example
  ansible/roles/jupyterhub/tasks/main.yml
  ansible/roles/jupyterhub/templates/jupyterhub_config_base.py.j2
Labels: feature

#308 DeepLinking request support to allow file selection
  ansible/roles/jupyterhub/files/jupyterhub_config_lti13.py
  ansible/roles/jupyterhub/files/share/templates/file_select.html
  ansible/roles/jupyterhub/templates/docker-compose.yml.j2
  ansible/roles/jupyterhub/templates/jupyterhub_config_base.py.j2
  src/illumidesk/authenticators/authenticator.py
  src/illumidesk/authenticators/constants.py
  src/illumidesk/authenticators/handlers.py
  src/illumidesk/authenticators/validator.py
  src/illumidesk/lti13/handlers.py
  src/tests/illumidesk/authenticators/test_lti13_validator.py
Labels: feature, lti13

#318 Update spawner extra kwargs
  ansible/roles/jupyterhub/templates/jupyterhub_config_base.py.j2
Labels: refactor

#324 Update CPU limit configuration option
  README.md
  ansible/group_vars/all.yml
  ansible/hosts.example
  ansible/roles/jupyterhub/templates/env.jhub.j2
  ansible/roles/jupyterhub/templates/jupyterhub_config_base.py.j2
Labels: feature

#326 Normalize the course-id value before set auth_state
  src/illumidesk/authenticators/authenticator.py
  src/tests/illumidesk/authenticators/test_lti13_authenticator.py
Labels: fix, lti13

#322 Add shutdown_on_logout config option
  README.md
  ansible/group_vars/all.yml
  ansible/hosts.example
  ansible/roles/jupyterhub/templates/env.jhub.j2
  ansible/roles/jupyterhub/templates/jupyterhub_config_base.py.j2
Labels: feature

#327 Update nbgrader version
  ansible/wisc-dev.xml
  src/setup.py
Labels: chore

#328 Fetch all lineitems using the pagination
  src/illumidesk/grades/senders.py
  src/tests/illumidesk/grades/test_senders.py
Labels: fix, lti13

#320 Add the shared folder by course
  ansible/roles/jupyterhub/templates/jupyterhub_config_base.py.j2
  src/illumidesk/spawners/hooks.py
  src/illumidesk/spawners/spawners.py
  src/tests/illumidesk/spawners/test_hooks.py
  src/tests/illumidesk/spawners/test_illumidesk_dockerspawner.py
Labels: feature, refactor

#333 Release v0.10.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/_version.py
Labels: chore

#335 Fix typo in hosts.example
  ansible/hosts.example
Labels: documentation

#337 Update default workspace image
  README.md
  ansible/group_vars/all.yml
Labels: dependencies, documentation
