Repository IllumiDesk/illumidesk, pull requests merged in 2020-04, with the labels that each got.

#1 CI/CD setup
  .flake8
  .pre-commit-config.yaml
  .travis.yml
  .travis/before_install.sh
  .travis/install.sh
  .travis/script.sh
  README.md
Labels: chore

#2 Create and upload coverage report
  .travis.yml
  .travis/after_success.sh
  .travis/script.sh
  README.md
  dev-requirements.txt
Labels: chore

#3 Add security policy document
  SECURITY.md
Labels: documentation

#4 Add contributing docs
  CONTRIBUTING.md
  LICENSE
  README.md
  docs/legal/corporate_contributor_license_agreement.md
  docs/legal/individual_contributor_license_agreement.md
Labels: documentation

#5 Update ansible setup instructions
  README.md
  ansible/roles/common/tasks/main.yml
Labels: bug, documentation

#6 Update standard launch url for LTI 1.1
  ansible/roles/illumidesk/templates/lti11-cartridge.xml.j2
Labels: fix

#7 Update lint configs
  .flake8
  tests/conftest.py
  tests/mocking.py
Labels: chore

#8 Simplify setup with make and new inventory file
  Makefile
  README.md
  ansible/hosts.example
  ansible/roles/common/tasks/main.yml
Labels: chore

#9 Pull Request template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: chore

#10 Update custom ansible-playbook command in Readme
  README.md
  ansible/group_vars/all.yml
  ansible/hosts.example
  ansible/roles/jupyterhub/files/share/templates/page.html
  ansible/roles/jupyterhub/templates/env.service.j2
Labels: documentation

#12 Run JupyterHub with Python 3.8
  ansible/roles/jupyterhub/tasks/main.yml
  ansible/roles/jupyterhub/templates/Dockerfile.jhub.j2
Labels: enhancement

#13 Update flake8 configuration settings
  .flake8
  Makefile
  src/illumidesk/apis/jupyterhub_api.py
  src/illumidesk/authenticators/authenticator.py
  src/illumidesk/authenticators/utils.py
  src/illumidesk/authenticators/validator.py
  src/illumidesk/spawners/spawner.py
  src/setup.py
Labels: chore

#14 Semantic release and changelog tools configuration
  .github/workflows/auto_merge_pr.yml
  .github/workflows/release.yml
  .travis/install.sh
  CHANGELOG.md
  package.json
Labels: chore

#15 Update changelog
  .github/workflows/auto_merge_pr.yml
  .github/workflows/release.yml
  CHANGELOG.md
  package.json
  src/_version.py
  src/setup.py
Labels: documentation

#16 Update make deploy command for one step setup
  Makefile
Labels: chore

#17 Lock requirements and update pre-commit-hooks
  .flake8
  .pre-commit-config.yaml
  dev-requirements.txt
  requirements.txt
  src/illumidesk/authenticators/validator.py
  src/setup.py
  tests/conftest.py
Labels: chore

#20 Update black and flake8 settings for improved compatibility
  .flake8
  .pre-commit-config.yaml
  .travis/script.sh
  CONTRIBUTING.md
  Makefile
  pyproject.toml
  src/illumidesk/apis/jupyterhub_api.py
  src/illumidesk/authenticators/authenticator.py
  src/illumidesk/authenticators/utils.py
  src/illumidesk/authenticators/validator.py
  src/illumidesk/spawners/spawner.py
  src/setup.py
Labels: chore

#25 Update readme and LTI options
  Makefile
  README.md
  ansible/group_vars/all.yml
  ansible/hosts.example
  ansible/provisioning.yml
  ansible/roles/jupyterhub/tasks/main.yml
  ansible/roles/setup_course/tasks/main.yml
Labels: documentation

#26 Release 0.2.0
  CHANGELOG.md
  package.json
Labels: chore

#27 Fix jupyterhub config
  ansible/roles/jupyterhub/tasks/main.yml
  src/_version.py
Labels: bug

#28 Update changelog for release 0.2.1
  CHANGELOG.md
  package.json
  src/_version.py
Labels: documentation

#29 Fixes the rules.toml file creation
  ansible/roles/jupyterhub/templates/docker-compose.yml.j2
  ansible/roles/reverse-proxy/tasks/main.yml
Labels: bug

#30 Release/0.2.2
  CHANGELOG.md
  package.json
  src/_version.py
Labels: chore

#31 Add curl to jupyterhub
  ansible/roles/jupyterhub/templates/Dockerfile.jhub.j2
Labels: dependencies
