Repository IllumiDesk/illumidesk, pull requests merged in 2020-07, with the labels that each got.

#168 Update authentication validation steps
  ansible/roles/illumidesk/templates/lti11-cartridge.xml.j2
  src/illumidesk/authenticators/constants.py
  src/illumidesk/authenticators/handlers.py
  src/illumidesk/authenticators/validator.py
  src/tests/illumidesk/authenticators/test_lti13_authenticator.py
  src/tests/illumidesk/authenticators/test_lti13_handlers.py
  src/tests/illumidesk/authenticators/test_lti13_validator.py
  src/tests/illumidesk/conftest.py
Labels: fix

#162 LTI 1.3 - Send grades
  ansible/roles/jupyterhub/files/jupyterhub_config_lti13.py
  src/illumidesk/authenticators/authenticator.py
  src/illumidesk/grades/__init__.py
  src/illumidesk/grades/exceptions.py
  src/illumidesk/grades/sender_controlfile.py
  src/illumidesk/grades/senders.py
  src/illumidesk/handlers/lms_grades.py
  src/illumidesk/handlers/lti.py
  src/illumidesk/lti13/__init__.py
  src/illumidesk/lti13/auth.py
  src/setup.py
  src/tests/illumidesk/authenticators/test_lti11_authenticator.py
  src/tests/illumidesk/authenticators/test_lti13_authenticator.py
  src/tests/illumidesk/conftest.py
  src/tests/illumidesk/factory.py
  src/tests/illumidesk/grades/__init__.py
  src/tests/illumidesk/grades/test_sender_controlfile.py
  src/tests/illumidesk/grades/test_senders.py
  src/tests/illumidesk/handlers/test_lms_grades_handler.py
  src/tests/illumidesk/handlers/test_lti13_config_handler.py
  src/tests/illumidesk/lti13/__init__.py
  src/tests/illumidesk/lti13/test_auth.py
  src/tests/illumidesk/setup_course/test_course.py
  src/tests/illumidesk/setup_course/test_utils.py
Labels: feature

#141 Add docstrings to lms_grades file
  src/illumidesk/apis/jupyterhub_api.py
  src/illumidesk/grades/senders.py
  src/illumidesk/handlers/lms_grades.py
  src/illumidesk/handlers/lti.py
  src/tests/illumidesk/apis/test_jupyterhub_api.py
  src/tests/illumidesk/conftest.py
  src/tests/illumidesk/factory.py
  src/tests/illumidesk/grades/test_sender_controlfile.py
  src/tests/illumidesk/grades/test_senders.py
  src/tests/illumidesk/handlers/test_lms_grades_handler.py
  src/tests/illumidesk/lti13/test_auth.py
Labels: documentation

#171 Adds a endpoint to expose only the JWKS (public key)
  ansible/roles/jupyterhub/files/jupyterhub_config_lti13.py
  src/illumidesk/apis/jupyterhub_api.py
  src/illumidesk/grades/senders.py
  src/illumidesk/handlers/lti.py
  src/tests/illumidesk/handlers/test_lti13_config_handler.py
  src/tests/illumidesk/handlers/test_lti13_jwks_handler.py
Labels: feature, lti13

#173 Set python interpreter in hosts file
  ansible/ansible.cfg
  ansible/hosts.example
Labels: fix

#176 Refactor to remove handlers module from the main package
  ansible/roles/jupyterhub/files/jupyterhub_config_lti11.py
  ansible/roles/jupyterhub/files/jupyterhub_config_lti13.py
  src/illumidesk/grades/handlers.py
  src/illumidesk/handlers/__init__.py
  src/illumidesk/lti13/handlers.py
  src/tests/illumidesk/grades/test_lms_grades_handler.py
  src/tests/illumidesk/handlers/__init__.py
  src/tests/illumidesk/lti13/test_lti13_config_handler.py
  src/tests/illumidesk/lti13/test_lti13_jwks_handler.py
Labels: lti13, refactor

#164 Support additional workspace types
  README.md
  ansible/group_vars/all.yml
  ansible/provisioning.yml
  ansible/roles/common/tasks/main.yml
  ansible/roles/jupyterhub/files/jupyterhub_config_fu.py
  ansible/roles/jupyterhub/files/jupyterhub_config_lti11.py
  ansible/roles/jupyterhub/files/jupyterhub_config_lti13.py
  ansible/roles/jupyterhub/files/requirements.txt
  ansible/roles/jupyterhub/templates/env.jhub.j2
  ansible/roles/nbgrader/tasks/main.yml
  ansible/roles/notebooks/tasks/main.yml
  ansible/roles/setup_course/files/Dockerfile
  ansible/roles/workspaces/notebooks/files/jupyter_notebook_config.py
  ansible/roles/workspaces/notebooks/files/requirements.txt
  ansible/roles/workspaces/notebooks/templates/Dockerfile.base.j2
  ansible/roles/workspaces/notebooks/templates/Dockerfile.grader.j2
  ansible/roles/workspaces/notebooks/templates/Dockerfile.instructor.j2
  ansible/roles/workspaces/notebooks/templates/Dockerfile.learner.j2
  ansible/roles/workspaces/rstudio/files/requirements.txt
  ansible/roles/workspaces/rstudio/files/rserver.conf
  ansible/roles/workspaces/rstudio/templates/Dockerfile.rstudio.j2
  ansible/roles/workspaces/tasks/main.yml
  ansible/roles/workspaces/theia/files/package.json
  ansible/roles/workspaces/theia/files/requirements.txt
  ansible/roles/workspaces/theia/files/run_theia.sh
  ansible/roles/workspaces/theia/templates/Dockerfile.theia.j2
  ansible/roles/workspaces/vscode/files/requirements.txt
  ansible/roles/workspaces/vscode/templates/Dockerfile.vscode.j2
  src/illumidesk/apis/jupyterhub_api.py
  src/illumidesk/authenticators/authenticator.py
  src/illumidesk/authenticators/constants.py
  src/illumidesk/grades/senders.py
  src/illumidesk/spawners/spawner.py
  src/illumidesk/spawners/spawners.py
  src/tests/illumidesk/authenticators/test_lti11_authenticator.py
  src/tests/illumidesk/authenticators/test_lti13_authenticator.py
  src/tests/illumidesk/conftest.py
  src/tests/illumidesk/factory.py
  src/tests/illumidesk/grades/test_lms_grades_handler.py
  src/tests/illumidesk/grades/test_sender_controlfile.py
  src/tests/illumidesk/spawners/test_illumidesk_dockerspawner.py
Labels: feature

#185 Release v0.8.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore

#186 Update changelog
  CHANGELOG.md
  src/_version.py
Labels: documentation

#187 Add java dependencies and jupyter kernel
  ansible/roles/workspaces/notebooks/templates/Dockerfile.base.j2
Labels: feature

#188 Update workspaces section with correct key and value example
  README.md
Labels: documentation

#190 Fix java kernel installation
  ansible/roles/workspaces/notebooks/templates/Dockerfile.base.j2
Labels: fix

#191 Update illumidesk-theia-proxy version
  ansible/roles/workspaces/theia/files/requirements.txt
Labels: chore

#192 Refactoring to simplify the logic in spawner classes
  ansible/roles/jupyterhub/files/jupyterhub_config_lti11.py
  ansible/roles/jupyterhub/files/jupyterhub_config_lti13.py
  src/illumidesk/spawners/hooks.py
  src/illumidesk/spawners/spawners.py
  src/tests/illumidesk/conftest.py
  src/tests/illumidesk/spawners/test_hooks.py
  src/tests/illumidesk/spawners/test_illumidesk_dockerspawner.py
Labels: lti11, refactor

#195 Update jhub and setup-course base images
  ansible/group_vars/all.yml
  ansible/roles/jupyterhub/templates/Dockerfile.jhub.j2
  ansible/roles/setup_course/files/Dockerfile
Labels: dependencies, refactor

#196 Refactor setup course image
  ansible/roles/setup_course/files/Dockerfile
Labels: refactor

#197 Update setup course service default CMD
  README.md
  ansible/roles/jupyterhub/templates/Dockerfile.jhub.j2
  ansible/roles/setup_course/files/Dockerfile
Labels: feature

#198 Normalize course label for lti 13
  src/illumidesk/authenticators/authenticator.py
Labels: fix

#199 Update setup-course microservice to use py3.8
  ansible/roles/jupyterhub/files/requirements.txt
  ansible/roles/setup_course/files/Dockerfile
  ansible/roles/setup_course/files/requirements.txt
  ansible/roles/setup_course/tasks/main.yml
  ansible/roles/setup_course/templates/Dockerfile.setup-course.j2
  dev-requirements.txt
  src/setup.py
Labels: feature

#200 Release 0.8.1
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  src/_version.py
Labels: chore

#201 Refactor normalize string method
  src/illumidesk/authenticators/authenticator.py
  src/illumidesk/authenticators/utils.py
  src/illumidesk/grades/handlers.py
  src/tests/illumidesk/authenticators/test_lti13_authenticator.py
  src/tests/illumidesk/authenticators/test_setup_course_hook.py
  src/tests/illumidesk/authenticators/test_utils.py
Labels: refactor

#207 Refactoring to change the factories methods to fixtures
  src/illumidesk/authenticators/authenticator.py
  src/illumidesk/authenticators/validator.py
  src/tests/illumidesk/authenticators/test_lti11_authenticator.py
  src/tests/illumidesk/authenticators/test_lti11_handlers.py
  src/tests/illumidesk/authenticators/test_lti11_validator.py
  src/tests/illumidesk/authenticators/test_lti13_authenticator.py
  src/tests/illumidesk/authenticators/test_lti13_handlers.py
  src/tests/illumidesk/authenticators/test_lti13_validator.py
  src/tests/illumidesk/authenticators/test_setup_course_hook.py
  src/tests/illumidesk/conftest.py
  src/tests/illumidesk/factory.py
  src/tests/illumidesk/grades/test_lms_grades_handler.py
  src/tests/illumidesk/grades/test_senders.py
  src/tests/illumidesk/lti13/test_lti13_config_handler.py
  src/tests/illumidesk/lti13/test_lti13_jwks_handler.py
  src/tests/illumidesk/mocks.py
Labels: tests

#212 Remove trailing ansible-lint config file
  .ansible-lint
Labels: chore

#209 Update notebook base image
  ansible/roles/workspaces/notebooks/files/jupyter_notebook_config.py
  ansible/roles/workspaces/notebooks/templates/Dockerfile.base.j2
Labels: fix

#210 Add additional grader dependencies
  ansible/roles/workspaces/notebooks/files/requirements.txt
Labels: dependencies

#213 Provide admin user option with ansible
  README.md
  ansible/group_vars/all.yml
  ansible/hosts.example
  ansible/roles/jupyterhub/files/jupyterhub_config_fu.py
  ansible/roles/jupyterhub/files/jupyterhub_config_lti11.py
  ansible/roles/jupyterhub/files/jupyterhub_config_lti13.py
  ansible/roles/jupyterhub/templates/env.jhub.j2
Labels: feature

#215 Refactor authenticators to always normalize usernames
  src/illumidesk/authenticators/authenticator.py
  src/tests/illumidesk/authenticators/test_lti11_authenticator.py
  src/tests/illumidesk/authenticators/test_lti13_authenticator.py
  src/tests/illumidesk/authenticators/test_utils.py
Labels: refactor

#219 Update LTI configs with admin user env var
  README.md
  ansible/group_vars/all.yml
  ansible/roles/jupyterhub/files/jupyterhub_config_lti11.py
  ansible/roles/jupyterhub/files/jupyterhub_config_lti13.py
  src/tests/illumidesk/conftest.py
Labels: fix

#216 Refactor authenticator argument validations
  src/illumidesk/authenticators/authenticator.py
  src/tests/illumidesk/authenticators/test_lti11_authenticator.py
Labels: refactor

#220 Fix the response of /jwks endpoint
  src/illumidesk/lti13/handlers.py
  src/tests/illumidesk/lti13/test_lti13_jwks_handler.py
Labels: fix, lti13

#222 Change the nbgrader template used by the setup_course service
  src/illumidesk/setup_course/constants.py
  src/tests/illumidesk/setup_course/test_course.py
Labels: bug, lti11, lti13

#223 Release version 0.8.2
  CHANGELOG.md
  package-lock.json
  package.json
  src/_version.py
  src/tests/illumidesk/setup_course/test_course.py
Labels: chore

#224 Add codeql security scanning workflow
  .github/workflows/codeql-analysis.yml
Labels: chore

#225 Update mark stale issues and pr's action
  .github/workflows/stale.yml
Labels: chore

#230 Fix template by adding a escape character in the nbgrader-template
  src/illumidesk/setup_course/constants.py
Labels: fix

#229 Pull workspace images from registry
  ansible/group_vars/all.yml
  ansible/roles/common/tasks/main.yml
  ansible/roles/jupyterhub/tasks/main.yml
  ansible/roles/workspaces/notebooks/files/jupyter_notebook_config.py
  ansible/roles/workspaces/notebooks/files/requirements.txt
  ansible/roles/workspaces/notebooks/templates/Dockerfile.base.j2
  ansible/roles/workspaces/notebooks/templates/Dockerfile.grader.j2
  ansible/roles/workspaces/notebooks/templates/Dockerfile.instructor.j2
  ansible/roles/workspaces/notebooks/templates/Dockerfile.learner.j2
  ansible/roles/workspaces/rstudio/files/requirements.txt
  ansible/roles/workspaces/rstudio/files/rserver.conf
  ansible/roles/workspaces/rstudio/templates/Dockerfile.rstudio.j2
  ansible/roles/workspaces/tasks/main.yml
  ansible/roles/workspaces/theia/files/package.json
  ansible/roles/workspaces/theia/files/requirements.txt
  ansible/roles/workspaces/theia/files/run_theia.sh
  ansible/roles/workspaces/theia/templates/Dockerfile.theia.j2
  ansible/roles/workspaces/vscode/files/requirements.txt
  ansible/roles/workspaces/vscode/templates/Dockerfile.vscode.j2
Labels: feature

#233 Update notebook environment variables in readme
  README.md
Labels: documentation

#231 Jupyterhub base url configuration
  ansible/group_vars/all.yml
  ansible/hosts.example
  ansible/roles/jupyterhub/files/jupyterhub_config_fu.py
  ansible/roles/jupyterhub/files/jupyterhub_config_lti11.py
  ansible/roles/jupyterhub/files/jupyterhub_config_lti13.py
  ansible/roles/jupyterhub/files/share/templates/page.html
  ansible/roles/jupyterhub/templates/env.jhub.j2
  ansible/roles/jupyterhub/templates/env.service.j2
  ansible/roles/setup_course/templates/env.setup_course.j2
  src/illumidesk/apis/announcement_service.py
  src/illumidesk/authenticators/authenticator.py
  src/illumidesk/setup_course/course.py
  src/tests/illumidesk/apis/test_announcement_service.py
  src/tests/illumidesk/authenticators/test_setup_course_hook.py
Labels: feature, lti11, lti13

#236 Update ansible playbook and constants to remove nbgrader configuration
  ansible/provisioning.yml
  ansible/roles/nbgrader/files/global_nbgrader_config.py
  ansible/roles/nbgrader/files/nbextensions/formgrader/main.js
  ansible/roles/nbgrader/files/server_extensions/formgrader/static/js/manage_assignments.js
  ansible/roles/nbgrader/files/server_extensions/formgrader/templates/base.tpl
  ansible/roles/nbgrader/files/server_extensions/formgrader/templates/manage_assignments.tpl
  ansible/roles/nbgrader/tasks/main.yml
  ansible/roles/nbgrader/templates/grader_course_nbgrader_config.py.j2
  ansible/roles/nbgrader/templates/grader_nbgrader_config.py.j2
  src/illumidesk/setup_course/constants.py
  src/illumidesk/setup_course/course.py
  src/tests/illumidesk/setup_course/test_course.py
Labels: feature, refactor

#237 Update docs and remove dangling templates
  README.md
  ansible/roles/jupyterhub/files/jupyterhub_config_fu.py
  ansible/roles/jupyterhub/files/requirements.txt
  ansible/roles/jupyterhub/tasks/main.yml
  ansible/roles/jupyterhub/templates/docker-compose.yml.j2
  ansible/roles/jupyterhub/templates/env.service.j2
Labels: documentation

#238 Simplify the jupyterhub config files
  README.md
  ansible/group_vars/all.yml
  ansible/hosts.example
  ansible/roles/jupyterhub/files/jupyterhub_config_base.py
  ansible/roles/jupyterhub/files/jupyterhub_config_lti11.py
  ansible/roles/jupyterhub/files/jupyterhub_config_lti13.py
  ansible/roles/jupyterhub/tasks/main.yml
  ansible/roles/jupyterhub/templates/Dockerfile.jhub.j2
  ansible/roles/jupyterhub/templates/env.jhub.j2
  src/illumidesk/apis/announcement_service.py
  src/illumidesk/apis/setup_course_service.py
  src/illumidesk/authenticators/authenticator.py
  src/tests/illumidesk/authenticators/test_setup_course_hook.py
Labels: lti11, lti13, refactor

#239 Update task to remove adding folders with common role
  README.md
  ansible/group_vars/all.yml
  ansible/hosts.example
  ansible/roles/common/tasks/main.yml
  ansible/roles/jupyterhub/files/jupyterhub_config_base.py
  ansible/roles/jupyterhub/templates/env.jhub.j2
Labels: feature

#241 fix: Update required claims and username value when private
  src/illumidesk/authenticators/authenticator.py
  src/illumidesk/authenticators/constants.py
  src/tests/illumidesk/authenticators/test_lti13_authenticator.py
  src/tests/illumidesk/authenticators/test_lti13_validator.py
  src/tests/illumidesk/conftest.py
Labels: fix

#244 Fixes the use of next url with lti13
  ansible/roles/jupyterhub/files/jupyterhub_config_lti13.py
  src/illumidesk/apis/setup_course_service.py
  src/illumidesk/authenticators/handlers.py
  src/tests/illumidesk/authenticators/test_lti13_handlers.py
Labels: feature, lti13

#249 Update ansible tasks with additional LTI 1.1 conditionals
  ansible/roles/illumidesk/tasks/main.yml
  ansible/roles/jupyterhub/tasks/main.yml
Labels: refactor

#251 Fix to determine what authenticator is used to submit grades
  src/illumidesk/grades/handlers.py
  src/tests/illumidesk/grades/test_lms_grades_handler.py
Labels: fix, lti11

#250 Clean setup.py dependencies
  Makefile
  ansible/roles/jupyterhub/files/requirements.txt
  src/setup.py
Labels: chore

#258 Update to resolve CVE-2020-8116
  package-lock.json
Labels: bug

#242 Release v0.8.3
  CHANGELOG.md
  package-lock.json
  package.json
  src/_version.py
Labels: chore
