Repository IllumiDesk/illumidesk, pull requests merged in 2020-06, with the labels that each got.

#95 Validates if 'lis_outcome_service_url' and 'lis_result_sourcedid' fields exist
  src/illumidesk/authenticators/authenticator.py
  src/tests/illumidesk/authenticators/test_lti11_authenticator.py
  src/tests/illumidesk/factory.py
Labels: fix

#96 Adds dependencies for plotly dash
  ansible/roles/notebooks/files/requirements.txt
Labels: dependencies, enhancement

#92 Tests for setup course hook
  src/illumidesk/authenticators/authenticator.py
  src/illumidesk/authenticators/constants.py
  src/illumidesk/authenticators/handlers.py
  src/illumidesk/authenticators/validator.py
  src/tests/illumidesk/authenticators/test_lti11_authenticator.py
  src/tests/illumidesk/authenticators/test_lti11_handlers.py
  src/tests/illumidesk/authenticators/test_lti13_authenticator.py
  src/tests/illumidesk/authenticators/test_lti13_handlers.py
  src/tests/illumidesk/authenticators/test_lti13_validator.py
  src/tests/illumidesk/authenticators/test_setup_course_hook.py
  src/tests/illumidesk/authenticators/test_utils.py
  src/tests/illumidesk/conftest.py
  src/tests/illumidesk/factory.py
  src/tests/illumidesk/handlers/test_lti13_config_handler.py
  src/tests/illumidesk/mocks.py
  src/tests/illumidesk/setup_course/test_app.py
  src/tests/illumidesk/setup_course/test_course.py
  src/tests/illumidesk/setup_course/test_utils.py
Labels: tests

#103 Release v0.7.0
  CHANGELOG.md
  package-lock.json
  package.json
  src/_version.py
Labels: chore

#100 Update base notebook hash commit
  ansible/group_vars/all.yml
  ansible/roles/notebooks/files/requirements.txt
  src/tests/illumidesk/authenticators/test_setup_course_hook.py
Labels: dependencies

#101 Update JupyterHub hash commit
  ansible/group_vars/all.yml
Labels: dependencies

#122 Update notebook image tag
  ansible/group_vars/all.yml
Labels: fix

#124 Release v0.7.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/_version.py
  src/illumidesk/handlers/lti.py
Labels: chore

#132 Update conditional in lti11 authenticator with Student string
  src/illumidesk/authenticators/authenticator.py
  src/tests/illumidesk/authenticators/test_lti11_authenticator.py
  src/tests/illumidesk/factory.py
Labels: fix

#137 Release 0.7.2
  CHANGELOG.md
  package-lock.json
  package.json
  src/_version.py
Labels: chore

#140 Switch default branch from master to main
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .travis.yml
  CONTRIBUTING.md
  README.md
  SECURITY.md
  codecov.yml
Labels: chore

#153 Clone and merge code located in remote git-based repositories with workspace launches
  README.md
  ansible/roles/jupyterhub/files/requirements.txt
  ansible/roles/notebooks/files/requirements.txt
  ansible/roles/notebooks/templates/Dockerfile.base.j2
  src/illumidesk/authenticators/authenticator.py
  src/illumidesk/authenticators/utils.py
  src/tests/illumidesk/authenticators/test_lti11_authenticator.py
  src/tests/illumidesk/authenticators/test_utils.py
Labels: feature

#139 Refactor LTI 1.3 login handler
  ansible/group_vars/all.yml
  pytest.ini
  src/illumidesk/authenticators/authenticator.py
  src/illumidesk/authenticators/constants.py
  src/illumidesk/authenticators/handlers.py
  src/illumidesk/authenticators/utils.py
  src/illumidesk/authenticators/validator.py
  src/tests/illumidesk/authenticators/test_lti13_handlers.py
  src/tests/illumidesk/conftest.py
  src/tests/illumidesk/factory.py
Labels: lti13, refactor

#154 Add FredAPI dependency
  ansible/roles/notebooks/files/requirements.txt
Labels: dependencies

#157 Release v0.7.3
  CHANGELOG.md
  package-lock.json
  package.json
  src/_version.py
Labels: chore

#159 Add support to use aws efs
  README.md
  ansible/group_vars/all.yml
  ansible/hosts.example
  ansible/roles/common/tasks/main.yml
Labels: feature

#161 Add new welcome messages
  .github/config.yml
Labels: chore

#166 Install nfs-common required by setups with NFS
  ansible/roles/common/tasks/main.yml
Labels: dependencies
