Repository IllumiDesk/illumidesk, pull requests merged in 2020-08, with the labels that each got.

#262 Udpate custom nbgrader to version 0.6.2
  src/setup.py
Labels: chore

#260 Automated assignment creation with LTI 1.3
  src/illumidesk/apis/nbgrader_service.py
  src/illumidesk/authenticators/authenticator.py
  src/illumidesk/grades/handlers.py
  src/illumidesk/grades/senders.py
  src/tests/illumidesk/authenticators/test_lti13_authenticator.py
  src/tests/illumidesk/authenticators/test_setup_course_hook.py
  src/tests/illumidesk/conftest.py
  src/tests/illumidesk/grades/test_senders.py
Labels: feature

#264 Fix: Normalize the assignment name and course-id
  src/illumidesk/apis/nbgrader_service.py
  src/illumidesk/authenticators/authenticator.py
  src/tests/illumidesk/apis/test_nbgrader_service_helper.py
Labels: fix

#266 Update template page texts
  ansible/roles/jupyterhub/files/share/templates/405.html
  ansible/roles/jupyterhub/files/share/templates/login.html
  ansible/roles/jupyterhub/files/share/templates/page.html
Labels: chore

#270 Fix source directory permissions
  src/illumidesk/apis/nbgrader_service.py
  src/tests/illumidesk/apis/test_nbgrader_service_helper.py
Labels: bug

#268 Handle unique usernames with the Canvas LMS
  src/illumidesk/authenticators/authenticator.py
  src/tests/illumidesk/authenticators/test_lti11_authenticator.py
  src/tests/illumidesk/conftest.py
Labels: feature

#271 Include users with TeachingAssistant role in the formgrade group
  src/illumidesk/authenticators/authenticator.py
  src/illumidesk/authenticators/constants.py
  src/illumidesk/authenticators/utils.py
  src/illumidesk/spawners/spawners.py
  src/tests/illumidesk/apis/test_announcement_service.py
  src/tests/illumidesk/authenticators/test_setup_course_hook.py
  src/tests/illumidesk/authenticators/test_utils.py
Labels: feature

#265 Automated assignment creation with LTI11
  src/illumidesk/apis/nbgrader_service.py
  src/illumidesk/authenticators/authenticator.py
  src/illumidesk/authenticators/utils.py
  src/tests/illumidesk/apis/test_nbgrader_service_helper.py
  src/tests/illumidesk/authenticators/test_lti11_authenticator.py
  src/tests/illumidesk/conftest.py
Labels: feature, lti11

#275 Revert "[Snyk] Security upgrade ansible from 2.9.11 to 2.10.0"
  requirements.txt
Labels: chore

#280 Update nbgitpuller version
  ansible/roles/jupyterhub/files/requirements.txt
Labels: chore

#278 Remove items related to the workspace types
  README.md
  ansible/group_vars/all.yml
  ansible/roles/jupyterhub/files/jupyterhub_config_lti11.py
  ansible/roles/jupyterhub/files/jupyterhub_config_lti13.py
  ansible/roles/jupyterhub/templates/env.jhub.j2
  ansible/roles/workspaces/tasks/main.yml
  src/illumidesk/authenticators/authenticator.py
  src/illumidesk/authenticators/constants.py
  src/illumidesk/spawners/hooks.py
  src/illumidesk/spawners/spawners.py
  src/tests/illumidesk/authenticators/test_lti11_authenticator.py
  src/tests/illumidesk/authenticators/test_lti13_authenticator.py
  src/tests/illumidesk/conftest.py
  src/tests/illumidesk/spawners/test_hooks.py
  src/tests/illumidesk/spawners/test_illumidesk_dockerspawner.py
Labels: documentation, refactor

#281 Create a shared folder between instructors and students
  README.md
  ansible/group_vars/all.yml
  ansible/hosts.example
  ansible/roles/jupyterhub/files/jupyterhub_config_base.py
  ansible/roles/jupyterhub/templates/env.jhub.j2
  ansible/roles/setup_course/templates/env.setup_course.j2
  src/illumidesk/setup_course/course.py
  src/illumidesk/spawners/spawners.py
  src/setup.py
  src/tests/illumidesk/setup_course/test_course.py
  src/tests/illumidesk/spawners/test_illumidesk_dockerspawner.py
Labels: feature

#283 Remove items related with unused grader role
  README.md
  ansible/roles/jupyterhub/templates/env.jhub.j2
  src/illumidesk/authenticators/authenticator.py
  src/illumidesk/spawners/spawners.py
  src/tests/illumidesk/conftest.py
  src/tests/illumidesk/spawners/test_illumidesk_dockerspawner.py
Labels: refactor

#288 Update dockerspawner configuration settings
  ansible/roles/jupyterhub/files/jupyterhub_config_base.py
  src/illumidesk/setup_course/course.py
  src/illumidesk/spawners/spawners.py
  src/tests/illumidesk/spawners/test_illumidesk_dockerspawner.py
Labels: feature

#289 Ensure pip is always up to date
  Makefile
Labels: chore

#298 Release v0.9.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore

#299 Update default JupyterHub configuration
  README.md
  ansible/group_vars/all.yml
  ansible/hosts.example
  ansible/roles/jupyterhub/files/jupyterhub_config_base.py
  ansible/roles/jupyterhub/files/jupyterhub_config_lti11.py
  ansible/roles/jupyterhub/files/jupyterhub_config_lti13.py
  ansible/roles/jupyterhub/templates/env.jhub.j2
Labels: feature

#300 Make sure the course directory exists
  src/illumidesk/grades/sender_controlfile.py
  src/tests/illumidesk/authenticators/test_lti11_authenticator.py
  src/tests/illumidesk/grades/test_sender_controlfile.py
Labels: bug, lti11

#301 Release 0.9.1
  CHANGELOG.md
  package-lock.json
  package.json
  src/_version.py
Labels: chore

#305 Add grader header and footer templates
  README.md
  ansible/wisc-dev.xml
  src/illumidesk/setup_course/constants.py
Labels: feature
