Repository IllumiDesk/illumidesk, pull requests merged in 2020-10, with the labels that each got.

#339 Use postgres with nbgrader
  Makefile
  README.md
  ansible/group_vars/all.yml
  ansible/hosts.example
  ansible/roles/jupyterhub/files/requirements.txt
  ansible/roles/jupyterhub/tasks/main.yml
  ansible/roles/jupyterhub/templates/docker-compose.yml.j2
  ansible/roles/jupyterhub/templates/env.jhub.j2
  ansible/roles/setup_course/files/requirements.txt
  ansible/roles/setup_course/templates/env.setup_course.j2
  src/illumidesk/apis/jupyterhub_api.py
  src/illumidesk/apis/nbgrader_service.py
  src/illumidesk/authenticators/authenticator.py
  src/illumidesk/grades/senders.py
  src/illumidesk/setup_course/constants.py
  src/illumidesk/setup_course/course.py
  src/tests/illumidesk/apis/test_jupyterhub_api.py
  src/tests/illumidesk/apis/test_nbgrader_service_helper.py
  src/tests/illumidesk/authenticators/test_setup_course_hook.py
  src/tests/illumidesk/conftest.py
  src/tests/illumidesk/grades/test_senders.py
  src/tests/illumidesk/setup_course/test_course.py
Labels: lti11, lti13, refactor

#341 Add universe for Ubuntu Focal
  ansible/roles/common/tasks/main.yml
Labels: fix

#344 Default to resourcelink for assignment placements
  src/illumidesk/lti13/handlers.py
Labels: chore

#345 Use one database for each course within the organization
  Makefile
  README.md
  ansible/roles/jupyterhub/templates/docker-compose.yml.j2
  ansible/roles/jupyterhub/templates/env.jhub.j2
  ansible/roles/setup_course/templates/env.setup_course.j2
  src/illumidesk/apis/nbgrader_service.py
  src/illumidesk/authenticators/authenticator.py
  src/illumidesk/grades/senders.py
  src/setup.py
  src/tests/illumidesk/apis/test_nbgrader_service_helper.py
  src/tests/illumidesk/conftest.py
Labels: feature, refactor

#352 Set USER_ROLE for shared grader notebooks
  .gitignore
  src/illumidesk/setup_course/course.py
  src/tests/illumidesk/conftest.py
  src/tests/illumidesk/setup_course/test_course.py
Labels: feature

#350 Update dependency locks with pip-compile
  .pre-commit-config.yaml
  .travis/install.sh
  CONTRIBUTING.md
  README.md
  ansible/roles/jupyterhub/files/requirements.txt
  dev-requirements.in
  dev-requirements.txt
  requirements.in
  requirements.txt
  src/requirements.txt
  src/setup.py
Labels: chore

#353 Update docs to handle template header / footer with assignments
  README.md
Labels: documentation

#348 Update spawner env vars, update fixtures, rename lti fixtures
  ansible/roles/jupyterhub/templates/jupyterhub_config_base.py.j2
  src/tests/illumidesk/conftest.py
  src/tests/illumidesk/grades/test_senders.py
  src/tests/illumidesk/lti13/test_auth.py
  src/tests/illumidesk/lti13/test_lti13_config_handler.py
  src/tests/illumidesk/lti13/test_lti13_jwks_handler.py
Labels: refactor

#360 Add missing env.common task and template
  README.md
  ansible/roles/jupyterhub/tasks/main.yml
  ansible/roles/jupyterhub/templates/env.common.j2
Labels: fix

#362 Refactor postgres container options
  ansible/roles/jupyterhub/templates/docker-compose.yml.j2
  ansible/roles/jupyterhub/templates/env.jhub.j2
  ansible/roles/jupyterhub/templates/jupyterhub_config_base.py.j2
  ansible/roles/setup_course/templates/env.setup_course.j2
  src/tests/illumidesk/apps/__init__.py
  src/tests/illumidesk/apps/test_jupyterhub_base_config.py
  src/tests/illumidesk/conftest.py
  src/tests/illumidesk/lti13/test_lti13_config_handler.py
Labels: refactor

#368 Update UID in pre spawn hook to set user folder permissions
  src/illumidesk/spawners/hooks.py
  src/tests/illumidesk/apps/test_jupyterhub_base_config.py
  src/tests/illumidesk/conftest.py
  src/tests/illumidesk/spawners/test_illumidesk_dockerspawner.py
Labels: fix

#369 Add default values for the LTI 1.1 authenticator
  ansible/group_vars/all.yml
Labels: refactor

#371 Check if the database exists and create it with SQLAlchemy
  ansible/group_vars/all.yml
  src/illumidesk/apis/nbgrader_service.py
  src/requirements.txt
  src/setup.py
Labels: refactor
